# Generated by Django 5.1.6 on 2025-05-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_advertiseinquiry_alter_comment_time_alter_post_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter_0', models.TextField(verbose_name='Planning Ki Hungama')),
                ('chapter_1', models.TextField(verbose_name='Safar Ka Shuruaat')),
                ('chapter_2', models.TextField(verbose_name='Pahaadon Ki Goanj')),
                ('chapter_3', models.TextField(verbose_name='Adventure Mode ON')),
                ('chapter_4', models.TextField(verbose_name='Yaadein Jo Hamesha Saath Rahengi')),
                ('chapter_5', models.TextField(blank=True, verbose_name='Photo Session Aur Reels Ki Duniya')),
                ('chapter_6', models.TextField(blank=True, verbose_name='Khaane Peene Ka Connection')),
                ('chapter_7', models.TextField(blank=True, verbose_name='Souvenir Shopping & Tofe Wale Moments')),
            ],
        ),
    ]
